### ISSUE TITLE
Sanitization problem in v3

### ISSUE THREAD

**Issue by AljosaB** [lekoala/silverstripe-excel-import-export#12]
Version: 3.0.0
SS version: 5.1.0

The new v3 version currently doesn't work for me. I'm getting this error
```
E_WARNING: Trying to access array offset on value of type int {"code":2,"message":"Trying to access array offset on value of type int","file":".../vendor/lekoala/silverstripe-excel-import-export/src/ExcelGridFieldExportButton.php","line":337} []
```

It seems like it's doing some sanitization there and expects $value  to be array but it isn't
```
// @link https://owasp.org/www-community/attacks/CSV_Injection
// [SS-2017-007] Sanitise XLS executable column values with a leading tab
if ($sanitize) {
    // If we have only one char we can make it simpler
    if ($sanitize_xls_chars_len === 1) {
        if ($value && $value[0] === $sanitize_xls_chars) {
            $value = "\t" . $value;
        }
    } else {
        if (preg_match('/^[' . $sanitize_xls_chars . '].*/', $value ?? '')) {
            $value = "\t" . $value;
        }
    }
}
```

The `$value` is being set in line 314 `$value = $gridField->getDataFieldValue($item, $columnSource);` where `$columnSource` is `ID` (it's safe to assume it'll be present in any type of object) and it's returning 1, which is probably the ID of the first record, but not array.

**Comment by lekoala** [comment]
i see, this is indeed not needed when the value is not a string
this should be fixed here https://github.com/lekoala/silverstripe-excel-import-export/releases/tag/3.0.1

**Comment by lekoala** [comment]
closing if it's all good feel free to reopen if there is more issues
