### ISSUE TITLE
SpreadCompat::ensureExtension causes tmp files to be missed

### ISSUE THREAD

**Issue by TheBnl** [lekoala/silverstripe-excel-import-export#13]
When calling the SpreadCompat read method while uploading an spreadsheet (in the ModelAdmin) the method `ensureExtension` causes the fileextension to be forced to an tmp file. This results in the file to be unfindable as the tmp file doesn't have an extension. 

Is the forced extension required or could it be omitted? 
```php
public static function read(
    string $filename,
    ...$opts
): Generator {
    $ext = $opts['extension'] ?? null;
    if ($ext) {
        // Errors on tmp files without an extension.
        // $filename = self::ensureExtension($filename, $ext);
    }
        
    return static::getAdapterForFile($filename, $ext)->readFile($filename, ...$opts);
}
```

**Comment by lekoala** [comment]
good catch, should be fixed, i've added a couple of tests to cover this

**Comment by lekoala** [comment]
closing
