### ISSUE TITLE
Improvement - move module to vendor folder

### ISSUE THREAD

**Issue by AljosaB** [lekoala/silverstripe-excel-import-export#4]
Please upgrade this module so that it installs inside vendor folder as described here -> https://docs.silverstripe.org/en/4/getting_started/directory_structure/#module_structure

**Comment by lekoala** [comment]
Yes I haven't made the move to convert my modules to vendor-modules yet, it's very convenient for me to install them outside of vendors as git submodules to work easily on them. Any pull request is welcome :-)

**Comment by Realys-31** [comment]
Hey leKoala. 
Very nice idea! I have install you're module with composer to test. I have a PHP FATAL ERROR.
For you're information, here is the trace log in apache2:

[php7:error] [pid 5663] [client 127.0.0.1:43876] PHP Fatal error:  Declaration of LeKoala\\ExcelImportExport\\ExcelGroupBulkLoader::processRecord($record, $columnMap, &$results, $preview = false) must be compatible with LeKoala\\ExcelImportExport\\ExcelBulkLoader::processRecord($record, $columnMap, &$results, $preview = false, $makeRelations = false) in /var/www/html/excel-import-export/code/ExcelGroupBulkLoader.php on line 0, referer: http://localhost/admin/pages/edit/show/84

[php7:error] [pid 14560] [client 127.0.0.1:43882] PHP Fatal error:  Declaration of LeKoala\\ExcelImportExport\\ExcelGroupBulkLoader::processRecord($record, $columnMap, &$results, $preview = false) must be compatible with LeKoala\\ExcelImportExport\\ExcelBulkLoader::processRecord($record, $columnMap, &$results, $preview = false, $makeRelations = false) in /var/www/html/excel-import-export/code/ExcelGroupBulkLoader.php on line 0

**Comment by lekoala** [comment]
it looks like the ExcelGroupBulkLoader is not up to date because it should already have the "makeRelations" argument (it does on master anyway). I've tagged 2.0.1 that should help you with composer.
