### ISSUE TITLE
Update release

### ISSUE THREAD

**Issue by t3hn0** [lekoala/silverstripe-excel-import-export#6]
Version 2.0.4 currently contains bug which prevents XLS(X) documents to contain header because $row is set to 1 after header is added to spreadsheet.

You already fixed issue with commit d40923b:  https://github.com/lekoala/silverstripe-excel-import-export/commit/d40923b46d34cb626d7d40622938beeadefada9f 

Could you create new release with this fix?

**Comment by lekoala** [comment]
version 2.0.5 has been released :-)
